FROM node:18 as build

ARG GENERATE_SOURCEMAP
ARG REACT_APP_GOOGLE_MAPS_API_KEY
ARG REACT_APP_BASE_URL
ARG REACT_APP_FRONT_URL
ARG REACT_APP_DOMAIN_URL
ARG REACT_APP_DASH_URL

ENV REACT_APP_GOOGLE_MAPS_API_KEY=$REACT_APP_GOOGLE_MAPS_API_KEY
ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL
ENV REACT_APP_FRONT_URL=$REACT_APP_FRONT_URL
ENV REACT_APP_DOMAIN_URL=$REACT_APP_DOMAIN_URL
ENV REACT_APP_DASH_URL=$REACT_APP_DASH_URL
ENV GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]