export const color = {
  PRIMARY_COLOR: "#F37A1D",
  SECONDARY_COLOR: "#18365A",
  BACKGROUND_COLOR: "#FFFFFF",
  TEXT_COLOR: "#18365A",
  LINK_COLOR: "#18365A",
  ERROR_COLOR: "",
  SUCCESS_COLOR: "",
  WARNING_COLOR: "",
  BORDER_COLOR: "",
};
