export const color = {
  PRIMARY_COLOR: "#111111",
  SECONDARY_COLOR: "#F2F2F2",
  BACKGROUND_COLOR: "#FFFFFF",
  TEXT_COLOR: "#111111",
  LINK_COLOR: "#111111",
  ERROR_COLOR: "",
  SUCCESS_COLOR: "",
  WARNING_COLOR: "",
  BORDER_COLOR: "",
};
