export const color = {
  PRIMARY_COLOR: "#FFFFFF",
  SECONDARY_COLOR: "#FFFFFF",
  BACKGROUND_COLOR: "#000000",
  TEXT_COLOR: "#FFFFFF",
  GRAY_TEXT_COLOR: "#AAAAAA",
  SECOND_TEXT_COLOR: "#FFFFFF",
  LINK_COLOR: "#FFFFFF",
  ERROR_COLOR: "",
  SUCCESS_COLOR: "",
  WARNING_COLOR: "",
  BORDER_COLOR: "",
};
