export const color = {
  PRIMARY_COLOR: "#d8b56c",
  SECONDARY_COLOR: "#fff",
  BACKGROUND_COLOR: "#0c0c0c",
  TEXT_COLOR: "#fff",
  GRAY_TEXT_COLOR: "#AAAAAA",
  SECOND_TEXT_COLOR: "#fff",
  LINK_COLOR: "#18365A",
  ERROR_COLOR: "",
  SUCCESS_COLOR: "",
  WARNING_COLOR: "",
  BORDER_COLOR: "",
};
